In [7]:
import numpy as np

In [9]:
lista = [1,2,3,4,5]

array = np.array(lista)

In [11]:
print(type(lista))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [15]:
arr_zeros = np.zeros(10)
print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
array[0] = 9
print(array)

[9 2 3 4 5]


In [25]:
matriz_zeros = np.zeros((5,3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [35]:
lista_de_notas = [9.8,5.6,7.8,9.1,6.5]
notas = np.array(lista_de_notas)
print('Máximo', notas.max())
print('Mínimo', notas.min())
print('Desvio Padrão', notas.std())
print('Média', notas.mean())
print('Posição menor', notas.argmin())

Máximo 9.8
Mínimo 5.6
Desvio Padrão 1.5628179676469045
Média 7.76
Posição menor 1
